--- 
title: "The Vermont Lottery"
date: "`r Sys.Date()`"
author: Michael Czekanski and Alex Lyford
site: bookdown::bookdown_site
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is analysis of the Vermont Lottery."
toc: true
abstract: "The prevailing belief is that scratch tickets are not worth playing, and this belief is often true --- but sometimes it isn't. In the Vermont Lottery specifically, we can identify times when scratch tickets are worth playing with an arbitrary level of confidence."
---

# Introduction

The prevailing belief is that scratch tickets are not worth playing, and this belief is often true --- but sometimes it isn't. In the Vermont Lottery specifically, we can identify times where scratch tickets are worth playing with an arbitrary level of confidence.

<!-- This is a _sample_ book written in **Markdown**. You can use anything that Pandoc's Markdown supports, e.g., a math equation $a^2 + b^2 = c^2$. -->

<!-- The **bookdown** package can be installed from CRAN or Github: -->

<!-- ```{r eval=FALSE} -->
<!-- install.packages("bookdown") -->
<!-- # or the development version -->
<!-- # devtools::install_github("rstudio/bookdown") -->
<!-- ``` -->

<!-- Remember each Rmd file contains one and only one chapter, and a chapter is defined by the first-level heading `#`. -->

<!-- To compile this example to PDF, you need XeLaTeX. You are recommended to install TinyTeX (which includes XeLaTeX): <https://yihui.org/tinytex/>. -->

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

df1 %>%
  ggplot(aes(x = ticketNum, y = ExpVal)) +
  geom_point(aes(color = factor(X7777)))
  
  simSapphire7Game <- function(){
  tickets <- createSapphire7Tickets()
  nTickets <- length(tickets)
  
  loser <- NULL
  seven <- NULL
  fifteen <- NULL
  twenty_five <- NULL
  seventy <- NULL
  seven_hundred <- NULL
  thousand <- NULL
  seven_777 <- NULL
  expVal <- NULL
  
  for(i in 1:nTickets){
    print(i)
    tickets <- tickets[-1]
    loser[i] <-sum(tickets == 0)
    seven[i] <- sum(tickets == 7)
    fifteen[i] <- sum(tickets == 15)
    twenty_five[i] <- sum(tickets == 25)
    seventy[i] <- sum(tickets == 70)
    seven_hundred[i] <- sum(tickets == 700)
    thousand[i] <- sum(tickets == 1000)
    seven_777[i] <- sum(tickets == 7777)
    expVal[i] <- mean(tickets))
  }
  
  
  
  simData <- data.frame(`Losers` = loser,
                        `7` = seven,
                        `15` = fifteen,
                        `25` = twenty_five,
                        `70` = seventy,
                        `700` = seven_hundred,
                        `1000` = thousand,
                        `7777` = seven_777,
                        `ExpVal` = expVal,
                        `ticketNum` = 1:nTickets)
  return(simData)
}
